export const BYTE_SECTIONS = [
  {
    label: "🧭 Strategic AI Awareness for Consultants",
    range: [1, 20],
  },
  {
    label: "🔧 Tactical AI for Daily Consulting Work",
    range: [21, 40],
  },
  {
    label: "🏗️ Leading AI Projects and Initiatives",
    range: [41, 60],
  },
  {
    label: "🧠 Advanced & Emerging Frontiers",
    range: [61, 80],
  },
];

export const BYTE_TITLES = [
  "The Real Meaning of AI for Today’s Consultant",
  "Beyond Hype: What Consultants Should Actually Know About AI",
  "Machine Learning vs. Management Thinking",
  "Automation Is Not AI — Stop Confusing the Two",
  "Why AI Is Reshaping How Clients Define Value",
  "The Language of AI: A Consultant’s Glossary",
  "AI Learning Methods (Supervised, Unsupervised, Reinforcement) Explained with Client Use Cases",
  "What Makes AI Work? Data Strategy Essentials",
  "Predict, Classify, Cluster: The Analytics Models That Matter",
  "Natural Language Processing: Where Clients Are Already Using It",
  "Computer Vision in Industry: What Consultants Need to Know",
  "Virtual Agents, Chatbots, and Client-Facing AI",
  "Strategy, Not Science: Where AI Fits in Business Models",
  "10 Ways AI Changes Traditional Consulting Deliverables",
  "Red Flags: Common AI Misconceptions That Derail Projects",
  "Responsible AI Isn’t Optional: What You Must Ask Clients",
  "Spotting and Addressing Bias in Models (Before the Client Does)",
  "Consultants as AI Translators: Turning Tech Into Strategy",
  "Good vs. Bad AI Use Cases — How to Tell Them Apart",
  "Field Recap: What Every Consultant Should Now Be Doing Differently",
  "Consultant AI Stack: Tools You Can Actually Use",
  "Structured vs. Unstructured Data: Mapping Sources to Client Needs",
  "The AI Pipeline from Raw Data to Strategic Insight",
  "Prompt Engineering for Consultants: Writing Requests That Work",
  "APIs: The New Consulting Interface to Client Systems",
  "No-Code AI Platforms: What’s Useful, What’s Not",
  "Using Copilots to Draft Strategy, Insights, and Playbooks",
  "When and How to Fine-Tune Models Without Touching Code",
  "Quick Wins: Embedding AI in Market Scans and Competitor Analysis",
  "Decision Trees and Forecasting Models in Real Client Deliverables",
  "Recommender Systems: Designing for Personalization at Scale",
  "Voice of the Customer: Using Sentiment Analysis in B2B",
  "AI-Powered Document Review and Extraction",
  "Excel Meets AI: Augmented Analysis for Power Users",
  "LLMs in Plain English: Capabilities, Limits, and Risks",
  "Scope Creep and Model Overpromise — Where Projects Go Wrong",
  "Case Study: How AI Changed the Digital Transformation Playbook",
  "Retrieval-Augmented Generation (RAG) for Knowledge Work",
  "The Consultant’s AI Toolkit: Core Capabilities to Offer Clients",
  "Building Reusable AI Frameworks for Future Engagements",
  "Planning and Running AI Projects with Strategic Intent",
  "How to Build a Client’s AI Strategy — End to End",
  "The AI Use Case Canvas: A Tool for Facilitating Alignment",
  "Conducting an AI Readiness Assessment That’s Not Just Lip Service",
  "Governance, Privacy, and Compliance in Client AI Initiatives",
  "Lean AI: Embedding AI in Process Improvement Work",
  "Financial Forecasting Models with Machine Learning",
  "ESG + AI: Driving Smarter Sustainability Metrics",
  "Government and Public Sector AI: Where Consultants Can Lead",
  "Agriculture and Natural Resource AI Applications in Canada",
  "What Consultants Should Know About Generative AI Across Domains",
  "AI + CRM: Personalizing Engagement Beyond Templates",
  "Model Explainability: Making Black Boxes Client-Safe",
  "ModelOps: Managing the Lifecycle of AI in Enterprises",
  "Establishing an AI Centre of Excellence for Clients",
  "Building a Responsible AI Governance Operating Model",
  "Running AI-Focused Design Thinking Workshops",
  "Trust-Building in AI Projects with Client Executives",
  "Building Business Cases for AI with Clarity and Credibility",
  "Prompt Engineering Deep Dive: Building Smart Input Templates",
  "The AI-Native Consultant: What Future-Ready Really Means",
  "Autonomous Agents in Workflow and Advisory Contexts",
  "Multi-Agent Collaboration for Complex Decision-Making",
  "Vector Databases and Enterprise Search for Consultants",
  "Scaling AI Use Across Large Organizations",
  "Using AI to Support Change Management and Culture Shifts",
  "Hyperautomation Strategy: RPA, AI, and Orchestration",
  "Positioning and Selling AI Projects with Confidence",
  "AI Co-Pilots as the New Analyst: The Consultant’s Edge",
  "Operating Model Design for AI-Native Clients",
  "AI for Knowledge Management and Internal IP Systems",
  "Behavioral AI: Nudges, Ethics, and Organizational Design",
  "Open Source vs. Proprietary AI: What Clients Should Know",
  "Creating Your Own AI Consultant Agent (Yes, You Can)",
  "Innovation Portfolios with AI: Frameworks and Examples",
  "Measuring ROI of AI Projects: Financial + Strategic Impact",
  "AI for Scenario Planning and Futures Thinking",
  "What’s Coming in AI Regulation — and What Clients Will Ask",
  "Becoming an AI Thought Leader Without Becoming a Technologist",
  "AI in M&A: Due Diligence, Integration, and Operational Synergy",
];